=== draganagrbic998/xml/schema_upgrade/osnova.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/draganagrbic998/xml/osnova"
    xmlns:osnova="https://github.com/draganagrbic998/xml/osnova">
    <xs:element name="Korisnik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="lozinka" type="xs:string"/>
                <xs:element minOccurs="0" ref="osnova:Gradjanin"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Gradjanin">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="osnova:Osoba"/>
                <xs:element ref="osnova:Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Osoba">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="prezime">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TPodnosenje">
        <xs:sequence>
            <xs:element ref="osnova:Gradjanin"/>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="detalji">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPodnosenjeDetalji">
        <xs:complexContent>
            <xs:extension base="osnova:TPodnosenje">
                <xs:sequence>
                    <xs:element name="kontakt">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="potpis" type="xs:base64Binary"/>
                    <xs:element name="odgovoreno" type="xs:boolean"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TOdgovaranje">
        <xs:sequence>
            <xs:element name="broj">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="datum" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== draganagrbic998/xml/backend-organ-vlasti/data/init/draganaasd@gmail.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<osnova:Korisnik xmlns:osnova="https://github.com/draganagrbic998/xml/osnova"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/draganagrbic998/xml/osnova file:/C:/Users/Dragana/Desktop/schema_upgrade/osnova.xsd">
    <osnova:email>draganaasd@gmail.com</osnova:email>
    <osnova:lozinka>$2a$10$aL2cRpbMvSsvTcIGxUoauO4RMefDmYtEEARsmKJpwJ7T585HfBsra</osnova:lozinka>
    <osnova:Gradjanin>
		<osnova:Osoba>
			<osnova:ime>Dragana</osnova:ime>
			<osnova:prezime>Grbic</osnova:prezime>
		</osnova:Osoba>
		<osnova:Adresa>
			<osnova:mesto>Novi Sad</osnova:mesto>
			<osnova:ulica>Lasla Gala</osnova:ulica>
			<osnova:broj>23</osnova:broj>
		</osnova:Adresa>
    </osnova:Gradjanin>
</osnova:Korisnik>
